fileshare/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from g_cloud import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    #path('', include('g_cloud.urls', namespace='g_cloud')),    
    path('g_cloud/', include('g_cloud.urls', namespace='g_cloud')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static('/templates/', document_root=settings.PROJECT_DIR + '/templates/')

#print(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

g_cloud/urls.py
from django.urls import path
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views

app_name = 'cloud'

urlpatterns = [
    path('folder_list/<int:file_name>/', views.download, name='download'),
    path('', views.photo_save, name='photo_save'),
    path('', views.new_folder, name='new_folder'),
    path('', views.file_upload, name='file_upload'),
    path('photo_save/', views.photo_save, name='photo_save'),
    path('new_folder/', views.new_folder, name='new_folder'),
    path('file_upload/', views.file_upload, name='file_upload'),
    path('test/', views.index, name='index'),
    path('', views.index, name='index'),
    path('g_cloud/', views.index, name='index'),
    
    path('files_list/<int:f>/', views.folder_list, name='folder_list'),
    path('files_list4/', views.files_list, name='files_list'),
    
    path('multi_file/', views.multi_file, name='multi_file'),
    path('', views.multi_file, name='multi_file'),
    path('dir_upload/', views.dir_upload, name='dir_upload'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='g_cloud/login.html'), name='login'),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

g_cloud/models.py
from django.contrib.auth.models import User
from django.db import models
#from django.conf import settings
#from django.core.files.storage import FileSystemStorage
from django import forms
###
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import os

# Create your models here.

class Folder(models.Model):
     folder = models.CharField(max_length=30)
     owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
     def __str__(self):
         return self.folder

class ImagePhoto(models.Model):
    photo = models.ImageField(upload_to = 'files/', default = 'media/images/users.jpg')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    def get_photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url
        else:
            return "images/users.png"
    def filename(self):
        print(self.photo.name)
        return os.path.basename(self.photo.name)

class Document(models.Model):
    upload = models.FileField(upload_to='files/', default = 'media/images/users.jpg')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    def filename(self):
        print(self.upload.name)
        return os.path.basename(self.upload.name)

class MultiFile(models.Model):
    uploads = models.FileField(upload_to='files/', default = 'media/images/users.jpg')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    def filename(self):
        print(self.uploads.name)
        return os.path.basename(self.uploads.name)

class DirUpload(models.Model):
    directory = models.FileField(upload_to='files/', default = 'media/images/users.jpg')
    title =  models.CharField(max_length=30)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    def filename(self):
        print(self.directory.name)
        return os.path.basename(self.directory.name)


     
     

     

g_cloud/forms.py
from django import forms
from django.forms import ClearableFileInput
from .models import ImagePhoto, Document, MultiFile, DirUpload, Folder
from django.contrib.auth.models import User


'''
class ImageForm(forms.ModelForm):
    folder = forms.ModelChoiceField(queryset=Folder.objects.filter(owner=18),
                                    to_field_name = 'folder',
                                    empty_label="Select Folder")
    class Meta:
        model = ImagePhoto
        fields = ['photo', 'folder',]
        photo = forms.ImageField()
    
    def __init__(self, *args, **kwargs):
         self.user = kwargs.pop('request',None)
         super(ImageForm, self).__init__(*args, **kwargs)
'''
class ImageForm(forms.ModelForm):
    class Meta:
        model = ImagePhoto
        fields = ('photo', 'folder',)

    def __init__(self, user, *args, **kwargs):
        super(ImageForm, self).__init__(*args, **kwargs)
        self.fields['folder'].queryset = Folder.objects.filter(owner=user.id)

         
class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('upload', 'folder',)
    
    def __init__(self, user, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        self.fields['folder'].queryset = Folder.objects.filter(owner=user.id)

class MultiFileForm(forms.ModelForm):
    class Meta:
        model = MultiFile
        fields = ['uploads',]
        widgets = {
            'uploads': ClearableFileInput(attrs={'multiple': True}),
        }
        
        
class FileFieldForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs=
        {'multiple': True, 'webkitdirectory': True, 'directory': True}))
        
        
class DirForm(forms.ModelForm):
    class Meta:
        model = DirUpload
        fields = ('title',)
        
      
class FolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ('folder',)
     

g_cloud/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import ImageForm, DocumentForm, MultiFileForm, DirForm, FolderForm
from .models import *
from django.template import RequestContext
import os
from django.http import StreamingHttpResponse
from wsgiref.util import FileWrapper
from django.http import FileResponse
import mimetypes
import urllib 
from django.http import HttpResponse
from django.utils.encoding import smart_str
from PIL import Image
#import PIL.Image
import shutil
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import ImagePhoto, Document, MultiFile, DirUpload, Folder
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import (
    LoginView,
)
# Create your views here.

def index(request):
    #print('...')
    if request.user.is_authenticated:
        files = Folder.objects.filter(owner=request.user)
        context = {'files': files}
        return render(request, 'g_cloud/index.html', context)
    else:
        return render(request, 'g_cloud/test.html')

@login_required
def photo_save(request, *args, **kwargs):
    
    if request.method != 'POST':
        # No data submitted create a blank form.
        form  = ImageForm(user=request.user)
    else:
        #POST data submitted; process data.
        form = ImageForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            new_image = form.save(commit=False)
            new_image.owner = request.user
            new_image.save()
            context = {'form': form}
            return render(request, 'g_cloud/new_photo.html', context)
    #print(form)
    context = {'form': form}
    return render(request, 'g_cloud/new_photo.html', context)
    
def current_user(request):
    return request.user.id
    
@login_required
def file_upload(request):
    if request.method != 'POST':
        form = DocumentForm(request.user)
    else:
        form = DocumentForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            new_file = form.save(commit=False)
            new_file.owner = request.user
            new_file.save()
            print(new_file.folder)
            context = {'form': form}
            return render(request, 'g_cloud/new_file.html', context)
    
    context = {'form': form}
    return render(request, 'g_cloud/new_file.html', context)
    
    
    
###
@login_required
def multi_file(request):
    if request.method != 'POST':
        form = MultiFileForm()
    else:
        form = MultiFileForm(request.POST, request.FILES)
        files = request.FILES.getlist('uploads')
        #files = request.FILES
        print(files)
        if form.is_valid():
             for f in files:
                  file_instance = MultiFile(uploads=f)
                  file_instance.owner = request.user
                  file_instance.save()
             file_instance.save()                   
    context = {'form': form}
    return render(request, 'g_cloud/multi_file.html', context)
    
@login_required
def files_list(request):
    files = Folder.objects.filter(owner=request.user)
    context = {'files': files}
    return render(request, 'g_cloud/files_list.html', context)
    #return render(request, 'g_cloud/index.html', context)

@login_required    
def download(request, file_name):
    try:
        t = DirUpload.objects.get(pk=file_name, owner=request.user)
        i = t.directory.url.split('/')
    except DirUpload.DoesNotExist:
         try:
             t = ImagePhoto.objects.get(id=file_name, owner=request.user)
             i = t.photo.url.split('/')
         except ImagePhoto.DoesNotExist:
             try:
                 t = Document.objects.get(id=file_name, owner=request.user)
                 i = t.upload.url.split('/')
             except Document.DoesNotExist:
                 return HttpResponse(status=404)
    file_path = settings.MEDIA_ROOT + i[-2] + '/' + i[-1]
    filename, file_extension = os.path.splitext(file_path)
    chunk_size = 8192
    if file_path.lower().endswith(('.png', '.jpg', '.jpeg')):
        response = StreamingHttpResponse(FileWrapper(open(file_path, 'rb'), chunk_size),
                           content_type=mimetypes.guess_type(file_path)[0])
        response['X-SendFile'] = smart_str(i[-1])
        response['Content-Length'] = os.path.getsize(file_path)    
        response['Content-Disposition'] = "attachment; filename=%s" % i[-1]
        return response
    else:
        fl = open(file_path, "r")
    file_wrapper = FileWrapper(file_path, 'rb')
    file_mimetype, _ = mimetypes.guess_type(file_path)
    response = HttpResponse(fl, content_type=file_mimetype )
    response['X-SendFile'] = smart_str(i[-1])
    response['Content-Length'] = os.stat(file_path).st_size
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(i[-1]) 
    return response
    
@login_required    
def folder_list(request, f, path=settings.MEDIA_ROOT):
    fldr = Folder.objects.get(id=f, owner=request.user)
    i = ImagePhoto.objects.filter(folder=f, owner=request.user)
    d = Document.objects.filter(folder=f, owner=request.user)
    du = DirUpload.objects.filter(title=fldr.folder, owner=request.user)
    files = []
    files.append(i)
    files.append(d)
    files.append(du)
    for f in files:
        print(f)
    
    
    context = { 'files' : files }
    return render(request, 'g_cloud/folder_list.html', context)
    
@login_required    
def dir_upload(request):
    if request.method != 'POST':
         fl = DirForm()
    else:
        fl = DirForm(request.POST, request.FILES)
        if fl.is_valid():
            tmp = fl.save(commit=False)
            for afile in request.FILES.getlist('directory'):          
                new_file = DirUpload(directory = afile)
                new_file.title = tmp.title 
                new_file.owner = request.user
                new_file.save()
            f = Folder(folder=new_file.title, owner=request.user)
            folder = f.save()
    context = {'fl' : fl}
    return render(request, 'g_cloud/dir_upload.html', context)

@login_required
def new_folder(request):
    if request.method != 'POST':
        form = FolderForm()
    else:
        form = FolderForm(request.POST)
        if form.is_valid():
             new_folder = form.save(commit=False)
             new_folder.owner = request.user
             new_folder.save()
    context = {'form' : form}
    return render(request, 'g_cloud/new_folder.html', context)


def rename(title):
    src = settings.MEDIA_ROOT + 'temp/'
    dst = settings.MEDIA_ROOT + title + '/'
    os.rename(src, dst)    

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Log the user in, and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            f = Folder(folder='images', owner=new_user)
            folder = f.save()
            j = Folder(folder='files', owner=new_user)
            folder2 = j.save()
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('g_cloud:index'))

    context = {'form': form}
    return render(request, 'g_cloud/register.html', context)


class login_view(LoginView):
    template_name = 'g_cloud/login.html'


def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('g_cloud:index'))



def del_():
     images = ImagePhoto.objects.all()
     for image in images:
         image.delete()
         print('...')
         
def del_dir():
    dirs = DirUpload.objects.all()
    for dir_ in dirs:
        dir_.delete()
        print('dir')
        print(dir_.id)     

def del5_():
    fs = Folder.objects.all()
    for f in fs:
        f.delete()

def del2_():
     docs = Document.objects.all()
     for doc in docs:
         doc.delete()
         print('...')

def del3_():
     mfs = MultiFile.objects.all()
     for mf in mfs:
         mf.delete()
         print('...')

def del4_():
     users = User.objects.all()
     for user in users:
         user.delete()


     

#del5_()
#del4_()
#del2_()
#del3_()
#del_()
#del_dir()

g_cloud/templates/g_cloud/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>G_cloud</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>
  
  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
          
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'g_cloud:index' %}">
              G cloud</a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'g_cloud:dir_upload' %}">Folder Upload</a></li>
            <li><a href="{% url 'g_cloud:file_upload' %}">File Upload</a></li>
            <li><a href="{% url 'g_cloud:photo_save' %}">Save Photo</a></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'g_cloud:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'g_cloud:register' %}">register</a></li>
              <li><a href="{% url 'g_cloud:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
        
      </div>
    </nav>
    
    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

g_cloud/templates/g_cloud/dir_upload.html
{% extends "g_cloud/base.html" %}
{% block content %}
 <form method="post" enctype="multipart/form-data">
   {% csrf_token %}
   {{ fl.as_p }} 
   <input type="file" name="directory" multiple = "true" webkitdirectory="true" directory = "true"/>
   <button type="submit">Upload</button>
</form>

{% endblock content %}

g_cloud/templates/g_cloud/files_list.html
{% extends "g_cloud/base.html" %}
{% block content %}
  <table border="1" colspan="2" width="100%">
     <tr>
       <th width="60%">File1</td>
       <th width="40%">Download1</td> 
     </tr>
   {% for file in files %}
     <tr>
       <td width="60%">{{file.folder}}</td>
       <td width="40%" align="center"><a href="{% url "g_cloud:folder_list"  file.id %}"> {{file.folder}}  </td></a>
     </tr>
   {% endfor %}  
  </table>
{% endblock content %}

g_cloud/templates/g_cloud/folder_list.html
{% extends "g_cloud/base.html" %}
{% block content %}

 {% for file in files %}
     {% for fi in files %}
       {% for f in fi %}
           <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
           <a href="{% url "g_cloud:download" f.id %}"
           <i class="fa fa-file-text" style="font-size:38px;color:blue"></i>
           <p style="margin-right:50px;font-size:11px">{{f.filename}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p></a> 
 {% endfor %}
   {% endfor %}
     {% endfor %}
 {% endblock content %}

g_cloud/templates/g_cloud/folder_upload.html
{% extends "g_cloud/base.html" %}
{% block content %}
<input type="hidden" name="dir_name" id="id_dir_name">
<input type="file" name="file" onchange="selectFolder(event)" webkitdirectory="" multiple="" required="" directory="" id="id_file">
{% endblock content %}

g_cloud/templates/g_cloud/image_list.html
{% extends "g_cloud/base.html" %}
{% block content %}
<table border="1" colspan="2" width="100%">
   <tr>
     <th width="60%">File</td>
     <th width="40%">Download</td> 
   </tr>
 {% for f in files %}
   <tr>
     <td width="60%">{{f}}</td>
     <td width="40%" align="center"><a href="{% url "g_cloud:download" f.id %}"> {{f}} </td></a>
   </tr>
 {% endfor %}
 </table>
{% endblock content %}

g_cloud/templates/g_cloud/index.html
{% extends "g_cloud/base.html" %}


{% block content %}
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <a href="{% url 'g_cloud:new_folder' %}">
  <i class="material-icons" style="font-size:36px;margin-left:900px;">create_new_folder</i>
  <p style="font-size:15px;margin-left:900px;">Create New Folder</p></a>
   
  
   
   {% for file in files %}

     <!DOCTYPE html>
     <html>
     <head>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
     <style type="text/css">
     .fa_custom {
     color: #003243
     }
     </style>
     </head>
     <body>
     <a href="{% url "g_cloud:folder_list" file.id %}"
     <i class=" fa fa-folder fa_custom fa-3x"></i>
     <p style="text-align:center;font-size:22px">{{file.folder}}&nbsp;&nbsp;&nbsp;</p></a>
     
     </body>
     </html>
   
   {% endfor %}  

{% endblock content %}

g_cloud/templates/g_cloud/login.html
{% extends "g_cloud/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock %}

{% block content %}
    
  <form method="post" action="{% url 'g_cloud:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'g_cloud:index' %}" />
  </form>
    
{% endblock content %}

g_cloud/templates/g_cloud/multi_file.html
{% extends "g_cloud/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Upload PDF</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="file" name="uploads" multiple = "true" webkitdirectory="true" directory = "true"/>
        <button type="submit" class="btn btn-primary">Upload Resumes</button>
    </form> 
{% endblock content %}

g_cloud/templates/g_cloud/new_file.html
{% extends "g_cloud/base.html" %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }} 
    <button type="submit">Create</button>
  </form>
{% endblock content %}

g_cloud/templates/g_cloud/new_folder.html
{% extends "g_cloud/base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save folder</button>
  </form>
{% endblock content %}

g_cloud/templates/g_cloud/new_photo.html
{% extends "g_cloud/base.html" %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }} 
    <button type="submit">Create</button>
  </form>




{% endblock content %}

g_cloud/templates/g_cloud/register.html
{% extends "g_cloud/base.html" %}

{% block content %}

  <form method="post" action="{% url 'g_cloud:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
        
    <button name="submit">register</button>
    <input type="hidden" name="next"
      value="{% url 'g_cloud:index' %}" />
  </form>
    
{% endblock content %}

g_cloud/templates/g_cloud/test.html
{% extends "g_cloud/base.html" %}
<p> you need to login or creat an account</p>